"use client"

import type { Group } from "./types"
import { calculateMemberBalances, simplifyDebts } from "./calculations"
import { getCurrencySymbol } from "./utils"

export async function generatePDF(group: Group): Promise<Blob> {
  const { jsPDF } = await import("jspdf")

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const currencySymbol = getCurrencySymbol(group.currency)
  let y = 20

  // Header
  doc.setFontSize(24)
  doc.setTextColor(22, 163, 74) // Green
  doc.text("EaseSplit Report", pageWidth / 2, y, { align: "center" })
  y += 15

  // Group Info
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text(group.name, pageWidth / 2, y, { align: "center" })
  y += 8

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Currency: ${group.currency} | Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, {
    align: "center",
  })
  y += 15

  // Summary
  const totalSpent = group.expenses.reduce((sum, e) => sum + e.amount, 0)
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text(`Total Expenses: ${currencySymbol}${totalSpent.toFixed(2)}`, 20, y)
  doc.text(`Members: ${group.members.length}`, 100, y)
  doc.text(`Expenses: ${group.expenses.length}`, 160, y)
  y += 15

  // Balances Table
  doc.setFontSize(14)
  doc.setTextColor(22, 163, 74)
  doc.text("Member Balances", 20, y)
  y += 8

  const balances = calculateMemberBalances(group)
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)

  // Table header
  doc.setFillColor(240, 240, 240)
  doc.rect(20, y - 4, pageWidth - 40, 8, "F")
  doc.text("Member", 25, y)
  doc.text("Paid", 80, y)
  doc.text("Owes", 110, y)
  doc.text("Net", 140, y)
  y += 8

  balances.forEach((balance) => {
    doc.text(balance.memberName, 25, y)
    doc.text(`${currencySymbol}${balance.totalPaid.toFixed(2)}`, 80, y)
    doc.text(`${currencySymbol}${balance.totalOwed.toFixed(2)}`, 110, y)
    const netColor = balance.netBalance > 0 ? [22, 163, 74] : balance.netBalance < 0 ? [220, 38, 38] : [100, 100, 100]
    doc.setTextColor(netColor[0], netColor[1], netColor[2])
    doc.text(`${balance.netBalance > 0 ? "+" : ""}${currencySymbol}${balance.netBalance.toFixed(2)}`, 140, y)
    doc.setTextColor(0, 0, 0)
    y += 6
  })
  y += 10

  // Settlements
  const settlements = simplifyDebts(balances)
  if (settlements.length > 0) {
    doc.setFontSize(14)
    doc.setTextColor(22, 163, 74)
    doc.text("Settlement Plan", 20, y)
    y += 8

    doc.setFontSize(10)
    doc.setTextColor(0, 0, 0)
    settlements.forEach((t) => {
      const fromName = group.members.find((m) => m.id === t.from)?.name || "Unknown"
      const toName = group.members.find((m) => m.id === t.to)?.name || "Unknown"
      doc.text(`${fromName} pays ${toName}: ${currencySymbol}${t.amount.toFixed(2)}`, 25, y)
      y += 6
    })
    y += 10
  }

  // Expenses List
  if (y > 240) {
    doc.addPage()
    y = 20
  }

  doc.setFontSize(14)
  doc.setTextColor(22, 163, 74)
  doc.text("Expense Details", 20, y)
  y += 8

  doc.setFontSize(9)
  doc.setTextColor(0, 0, 0)

  group.expenses.forEach((expense) => {
    if (y > 270) {
      doc.addPage()
      y = 20
    }

    const payer = group.members.find((m) => m.id === expense.payerId)?.name || "Unknown"
    doc.setFontSize(10)
    doc.text(`${expense.title} - ${currencySymbol}${expense.amount.toFixed(2)}`, 25, y)
    y += 5
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 100)
    doc.text(`Paid by ${payer} | ${expense.date} | ${expense.category} | ${expense.splitType}`, 25, y)
    doc.setTextColor(0, 0, 0)
    y += 8
  })

  // Footer
  const pageCount = doc.internal.pages.length - 1
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${pageCount} | Generated by EaseSplit`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" },
    )
  }

  return doc.output("blob")
}

export async function downloadPDF(group: Group) {
  const blob = await generatePDF(group)
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${group.name.replace(/\s+/g, "-")}-report.pdf`
  a.click()
  URL.revokeObjectURL(url)
}
